Feature/initialization app
street-coin/app pull request #1
Opened 2020-11-27 16:56 UTC by julieSalha

2020-11-28 19:36 UTC, luctst requested changes
@julieSalha Du coup faut que tu changes quelques trucs dans l'ensemble c'est:
* que tu enléves de l'index git les fichiers suivants: **package-lock.json** **db.json** **yarn.lock**, pour faire ça tu peux entrer la commande suiante: `git  rm --cached <filename>`.
* json-server on a pas besoin puisqu'on va utiliser l'api, du coup tu peux delete la dependences json-server en entrant cette commande dans ton terminal. `npm uninstall json-server`.

2020-11-29 10:48 UTC, julieSalha commented
Merci pour tes retours Lucas, j'ai retiré de l'index git les 3 fichiers
Pourquoi ne pas indexer package-lock.json et yarn.lock ?
J'en ai profité pour installé axios ;-)

2020-11-29 19:02 UTC, luctst commented
> Merci pour tes retours Lucas, j'ai retiré de l'index git les 3 fichiers
> Pourquoi ne pas indexer package-lock.json et yarn.lock ?
> J'en ai profité pour installer axios ;-)

Alors on pourrait gader les fichiers mais ils sont gros et ils prennent de la place :).

2020-11-29 19:02 UTC, luctst approved these changes

2020-11-29 19:02 UTC, merged