update readme
street-coin/app pull request #3
Opened 2020-12-13 13:09 UTC by julieSalha

Hello Lucas ;-)

J'ai updaté la structure du projet en reprenant un autre projet.
ça fonctionne ;-)
Etant donné que j'ai d'abord supprimé l'ancienne structure, on ne m'a demandé de review.

J'ai remis ça en place.

Les routes principales :  
/ => home
/sc-admin => admin

Tu me diras si tu veux que je change ça ;-)

Dispo dans l'aprem si tu as des retours.

2020-12-14 17:44 UTC, julieSalha commented
PS : j'ai commencé l'intégration mobile first ;-)

2020-12-15 14:42 UTC, luctst requested changes

2020-12-15 14:42 UTC, luctst commented on src/components/Login.vue
> +      axios
On va faire une config pour axios de maniére à ce que dans les composants one stjusyte à faire les calls APIe t pas  gérer toute autre logique  genre mettre le token dans le storage etc.. 
Tu peux créer un dossier `utils` et crée un fichier api.js je t'expliquerai ce qu'on va mettre.

2020-12-15 14:42 UTC, luctst commented on src/components/Login.vue
> +    login() {
On va utiliser async / await pour gérer les promesses c'est plus lisible et plus intuitive :)

2020-12-15 16:47 UTC, julieSalha commented on src/components/Login.vue
> +      axios
Done ;-)

2020-12-15 17:54 UTC, julieSalha commented
It's OK Lucas ;-)
Pour Axios on attend que l'API soit en place ?
La structure de la home en mobile est en place ;-)
Bonne soirée

2020-12-16 10:34 UTC, luctst approved these changes

2020-12-16 10:34 UTC, merged