Feature/font strucuture
street-coin/app pull request #5
Opened 2020-12-18 08:31 UTC by julieSalha

Je n'ai pas encore terminé de travailler sur la branche mais comme j'ai installé la nouvelle configuration, je préfère être au même niveau :-)

2020-12-18 10:29 UTC, luctst requested changes
N'oublie pas de pull les modifs de la branche `main` vers ta branche `feature/font-structure` y'a des conflits je crois.

2020-12-18 10:29 UTC, luctst commented on src/components/Header.vue
> +            <Navbar/>
```suggestion
            <navbar></navbar>
```

C'est mieux dans le template d'appeler les composants comme ça c'est une convention Vue :)

2020-12-18 10:29 UTC, luctst commented on src/components/Navbar.vue
> +            :src="require('@/assets/logo.svg')"
ça marche pas sans le `require()` ?

2020-12-18 16:41 UTC, julieSalha commented on src/components/Header.vue
> +            <Navbar/>
Je suis bien à jour avec main Lucas, j'ai normalement réglé tous les confilts.
Je note pour la convention Vue :-)

ça marche pour la navbar <navbar></navbar>
mais dans App.  ni <footer></footer> ni <header></header> ne fonctionnent.  tu saurais pourquoi ?

Sinon l'intégration de base est en place :-)

2020-12-18 16:44 UTC, julieSalha commented on src/components/Navbar.vue
> +            :src="require('@/assets/logo.svg')"
Négatif Monsieur, c'est du code la librairie Buefy, ça pourra évoluer par la suite.
C'est génant ? ;-)

2021-01-12 09:27 UTC, luctst requested changes

2021-01-12 09:27 UTC, luctst commented on .env
> +API_URL_DEV = 'http://localhost:9229'
Le fichier `.env` ne doit pas  être dans le github

2021-01-12 09:27 UTC, luctst commented on .eslintrc.js
> +    'space-before-blocks' : 0,
Faut qu'on évite de trop modifier le `eslint` en vrai on peut facilement fixer les problémes y'aun script qui fait ça dans le package.json je crois

2021-01-12 09:27 UTC, luctst commented on src/components/Footer.vue
>      Navbar
Pas besoin d'importer le compo navbar si on ll'utilise pas.

2021-01-12 09:27 UTC, luctst commented on src/components/Login.vue
> +      const authentification = {
POur la logique API j'ai crée une config axios que l'on va importer dans chaque requête que l'on va faire. Si tu veux checker c'est le fichier api dans `utils` il me semble.

2021-01-12 09:27 UTC, luctst commented on src/views/ProfileCard.vue
> +    profile: Object
```suggestion
    profile: {
      type: Object
    }
```

2021-01-12 09:42 UTC, julieSalha commented on .env
> +API_URL_DEV = 'http://localhost:9229'
C'est corrigé @luctst  ;-)

2021-01-15 12:42 UTC, luctst approved these changes

2021-01-15 12:44 UTC, merged